// The plain-text half of every email we send.
//
// Resend takes `html` and `text` separately and sends whatever it is given.
// We were giving it html alone, so every message went out as a single-part
// HTML mail. Filters read that as a spam signal on its own: legitimate senders
// send multipart/alternative, and bulk senders cutting corners do not. It also
// means anyone reading in a plain-text client, or a screen reader set to
// prefer text, got the raw markup or nothing.
//
// This derives the text part from the html rather than asking each template to
// write both. Two copies of the same sentence drift, and the one nobody looks
// at drifts first. The cost is that this has to understand our markup, which
// it can afford to: the emails are tables, headings, paragraphs, lists and
// links, all generated by us.
//
// Links become "label (url)" because a URL a reader cannot click is only
// useful if they can copy it.

/** Named and numeric entities our templates actually emit. */
function decodeEntities(s: string): string {
  return s
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d)))
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)));
}

export function htmlToText(html: string): string {
  let s = html;

  // Anything that is not prose, including the <head> and the wordmark image.
  s = s.replace(/<!DOCTYPE[^>]*>/gi, "");
  s = s.replace(/<head[\s\S]*?<\/head>/gi, "");
  s = s.replace(/<(script|style)[\s\S]*?<\/\1>/gi, "");

  // A link keeps its address. Done before tags are stripped, or the href is
  // gone by the time we want it. An anchor whose label already is the URL is
  // left alone rather than printed twice.
  s = s.replace(
    /<a\b[^>]*href\s*=\s*["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi,
    (_m, href: string, label: string) => {
      const text = decodeEntities(label.replace(/<[^>]*>/g, "")).trim();
      if (!text) return href;
      return text === href ? text : `${text} (${href})`;
    },
  );

  // Block boundaries become line breaks before the tags themselves go.
  s = s.replace(/<br\s*\/?>/gi, "\n");
  // The list opens a block; each item ends its own line. Marking the open tag
  // as well would put a blank line between every bullet.
  s = s.replace(/<(ul|ol)\b[^>]*>/gi, "\n");
  s = s.replace(/<li\b[^>]*>/gi, "- ");
  s = s.replace(/<\/li\s*>/gi, "\n");
  s = s.replace(/<\/(p|div|h1|h2|h3|tr|ul|ol|table)\s*>/gi, "\n\n");
  s = s.replace(/<(p|div|h1|h2|h3|table|tr)\b[^>]*>/gi, "\n");
  // A table cell is a column, not a paragraph: the item card puts a photo and
  // a name side by side and they should read as one line.
  s = s.replace(/<\/t[dh]\s*>/gi, " ");

  s = s.replace(/<[^>]*>/g, "");
  s = decodeEntities(s);

  // Whitespace last, so the breaks introduced above survive the tidy-up.
  s = s.replace(/[ \t ]+/g, " ");
  s = s.split("\n").map((line) => line.trim()).join("\n");
  s = s.replace(/\n{3,}/g, "\n\n");

  return s.trim();
}
